apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-blue
  labels:
    app: blue
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Blue Page</title>
        <style>
            body { background-color: #007bff; color: white; font-family: sans-serif; text-align: center; padding-top: 100px; }
        </style>
    </head>
    <body>
        <h1>Welcome to the Blue Page!</h1>
    </body>
    </html>
  