{{- if eq (index .Values.currentTarget "app") "blue" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-app.fullname" . }}-blue
  labels:
    {{- include "test-app.labels" . | nindent 4 }}
    {{- toYaml .Values.currentTarget | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.currentTarget | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.currentTarget | nindent 8 }}
        {{- include "test-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP    
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: html-volume
          configMap:
            name: configmap-blue
{{- end }}
